services:
  tttm:
    image: ghcr.io/ogrodje/tttm:latest
    ports:
      - "0.0.0.0:7778-7785:7777"
    restart: always
    environment:
      DATABASE_URL: jdbc:postgresql://pg:5432/tttm
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USER: postgres
    command: [ "server", "-P", "7777" ]
    links: [ pg ]
    depends_on: [ pg ]

  tournament:
    image: ghcr.io/ogrodje/tttm:latest
    environment:
      DATABASE_URL: jdbc:postgresql://pg:5432/tttm
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USER: postgres
    links: [ pg ]
    depends_on: [ pg ]
    restart: unless-stopped
    deploy: { replicas: 0 }
    command: [ "tournament", "--number-of-games", "10", "--store-results", "false" ]

  pg:
    image: postgres:17
    restart: always
    ports:
      - "0.0.0.0:5439:5432"
    environment:
      POSTGRES_DB: "tttm"
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}