name: Build && Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: shimataro/ssh-key-action@v2
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          known_hosts: unnecessary
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa_og_events
          config: |
            Host low
              User oto
              Hostname oto.srv4all.net
              IdentityFile ~/.ssh/id_rsa_og_events
              StrictHostKeyChecking no
              ConnectTimeout 60
              ConnectionAttempts 2
          if_key_exists: fail

      - uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'sbt'

      - uses: sbt/setup-sbt@v1

      - run: sbt "test"

      - run: sbt "docker:publish"
        if: ${{ github.ref == 'refs/heads/master' }}

      - name: Deploy to production
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          export DOCKER_HOST="ssh://low"
          ./bin/tttm-prod.sh pull && \
            ./bin/tttm-prod.sh up -d --remove-orphans

      - uses: sarisia/actions-status-discord@v1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          username: tttm-ci-bot
